# Generated by Django 2.1.5 on 2019-02-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop101', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='product_untitled', max_length=100),
            preserve_default=False,
        ),
    ]
